app_name = "custom_crm_integration"
app_title = "Custom CRM Integration"
app_publisher = "Global Tritorc"
app_description = "Custom logic for multi-company ERPNext integration."
app_version = "0.0.1"
app_license = "MIT"